### ISSUE TITLE
Ngrx selector

### ISSUE THREAD

**Issue by ghost** [joshuamorony/ngrx-ionic-example#1]
@joshuamorony 
Working with Angular 13+ and Ngrx 13+ gives the following error when I try to select selectAllTods:

![image](https://user-images.githubusercontent.com/69347197/157090243-25e1872c-4610-4893-b42e-5b3097962fe3.png)

**Comment by AdamBOD** [comment]
> @joshuamorony Working with Angular 13+ and Ngrx 13+ gives the following error when I try to select selectAllTods:
> 
> ![image](https://user-images.githubusercontent.com/69347197/157090243-25e1872c-4610-4893-b42e-5b3097962fe3.png)

You must give the AppState type to the store object in the constructor of your component

`constructor(private store: Store<AppState>) {}`
